FROM nginx:alpine
LABEL maintainer="Martinsl <https://github.com/Martinsl>"

ARG HUID=1000
ARG HGID=1000

ENV HUID ${HUID}
ENV HGID ${HGID}
ENV TERM xterm

RUN apk --no-cache add shadow \
    && usermod -u ${HUID} nginx \
    && groupmod -g ${HGID} nginx
